name: Wake Up Streamlit App

on:
  schedule:
    - cron: '0 */12 * * *' # Jalan setiap 12 jam
  workflow_dispatch:

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -L "https://YOUR-APP-NAME.streamlit.app" > /dev/null
